//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proje_Konfeksiyon
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBEntities : DbContext
    {
        public DBEntities()
            : base("name=DBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<tbl_HareketTipi> tbl_HareketTipi { get; set; }
        public virtual DbSet<tbl_Kategori> tbl_Kategori { get; set; }
        public virtual DbSet<tbl_Musteri> tbl_Musteri { get; set; }
        public virtual DbSet<tbl_TedarikciKayit> tbl_TedarikciKayit { get; set; }
        public virtual DbSet<tbl_UstKategori> tbl_UstKategori { get; set; }
        public virtual DbSet<tbl_KumasCinsi> tbl_KumasCinsi { get; set; }
        public virtual DbSet<tbl_KumasAlis> tbl_KumasAlis { get; set; }
        public virtual DbSet<tbl_Hareket> tbl_Hareket { get; set; }
        public virtual DbSet<tbl_KumasAlimGecmisi> tbl_KumasAlimGecmisi { get; set; }
        public virtual DbSet<tbl_UretimGecmisi> tbl_UretimGecmisi { get; set; }
        public virtual DbSet<tbl_Satis> tbl_Satis { get; set; }
        public virtual DbSet<tbl_Uretim> tbl_Uretim { get; set; }
        public virtual DbSet<tbl_KulKayit> tbl_KulKayit { get; set; }
        public virtual DbSet<tbl_yetki> tbl_yetki { get; set; }
    }
}
