//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proje_Konfeksiyon
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_KumasAlimGecmisi
    {
        public int Kumas_Stok_ID { get; set; }
        public Nullable<int> TedarikciID { get; set; }
        public Nullable<int> Miktar_KG_ { get; set; }
        public Nullable<decimal> Alis_Fiyat_TL_ { get; set; }
        public Nullable<System.DateTime> Tarih { get; set; }
        public Nullable<int> StokKoduID { get; set; }
        public Nullable<int> KumasCinsi { get; set; }
    }
}
