//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proje_Konfeksiyon
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Hareket
    {
        public int ID { get; set; }
        public Nullable<int> HareketID { get; set; }
        public Nullable<int> MusteriID { get; set; }
        public Nullable<int> KumasCinsiID { get; set; }
        public Nullable<int> UrunID { get; set; }
        public Nullable<int> StokID { get; set; }
        public Nullable<int> GirisKG { get; set; }
        public Nullable<int> UretimKG { get; set; }
        public Nullable<int> SatisKG { get; set; }
    }
}
