//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proje_Konfeksiyon
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Satis
    {
        public int SiparisID { get; set; }
        public Nullable<int> UrunID { get; set; }
        public Nullable<int> MusteriID { get; set; }
        public Nullable<int> Adet { get; set; }
        public Nullable<decimal> SatisFiyati { get; set; }
        public Nullable<System.DateTime> Tarih { get; set; }
        public Nullable<int> KumasCinsiID { get; set; }
        public Nullable<int> StokKoduID { get; set; }
        public Nullable<int> Miktar_KG_ { get; set; }
        public Nullable<int> BirimFiyati { get; set; }
        public Nullable<int> KDV { get; set; }
        public Nullable<int> KarOrani { get; set; }
    }
}
