//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proje_Konfeksiyon
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_yetki
    {
        public int ID { get; set; }
        public string Yetki { get; set; }
        public Nullable<int> KayitIslemleri { get; set; }
        public Nullable<int> Alis_Satis { get; set; }
        public Nullable<int> Stok { get; set; }
        public Nullable<int> Raporlar { get; set; }
        public Nullable<int> Hareket { get; set; }
        public Nullable<int> Kul_Kayit { get; set; }
    }
}
