//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proje_Konfeksiyon
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_KulKayit
    {
        public int Kul_ID { get; set; }
        public string Kul_Ad { get; set; }
        public string Sifre { get; set; }
        public string Kul_Tel_No { get; set; }
        public string E_Posta { get; set; }
        public string Adres { get; set; }
        public string Unvani { get; set; }
        public Nullable<int> YetkiID { get; set; }
        public string Ad_Soyad { get; set; }
    }
}
