//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proje_Konfeksiyon
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Musteri
    {
        public int musteriID { get; set; }
        public string Musteri_Ad_Soyad { get; set; }
        public string Musteri_Adres { get; set; }
        public Nullable<int> Musteri_Tel_No { get; set; }
    }
}
