//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proje_Konfeksiyon
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_TedarikciKayit
    {
        public int TedarikciID { get; set; }
        public string Firmaİsmi { get; set; }
        public string FirmaAdres { get; set; }
        public Nullable<int> Firma_Tel_No { get; set; }
    }
}
