//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proje_Konfeksiyon
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_UstKategori
    {
        public int ID { get; set; }
        public string UstKategoriAdi { get; set; }
    }
}
